### PR TITLE
upgrade to league/flysystem to 2.x and 3.x

### LINKED ISSUE #12: Upgrade to flysystem v2

### PR DESCRIPTION
**Pull request by petrparolek**
close #12

### CODE REVIEW

**Comment by solcik** [comment]
@petrparolek could you add `v3` to composer?

- https://blog.frankdejonge.nl/flysystem-3-0-0-is-released/
- https://flysystem.thephpleague.com/docs/what-is-new/

I reviewed these changes and it looks good for me.

@f3l1x can we merge this?

**Comment by f3l1x** [comment]
I didn't have time to test v2. Do you say its working in your apps?

**Comment by solcik** [comment]
> I didn't have time to test v2. Do you say its working in your apps?

There are BC breaks between versions.

So I would suggest to leave current version for v1.

Make a new tag v1.0.0 for Flysystem's versions v2 and v3, because not all people have Flysystem as direct dependency in composer, so we do not want them to install new version of this package accidentally with new version of Flysystem, to break their apps?

**Comment by petrparolek** [comment]
@solcik  I removed support of version 1.x.

**Comment by solcik** [comment]
@f3l1x ping, za mě daný PR funguje.)

**Comment by f3l1x** [comment]
Resolved #15

**Pull request closed without merging**
